### ISSUE TITLE
Doesn't work if custom $beforeInsert, $beforeUpdate are defined.

### ISSUE THREAD

**Issue by rmuratov** [scoutforpets/objection-password#16]
Hey! Here is my setup. In this case password still plaintext after insert. If I remove timestamps from schema and remove custom `$beforeInsert`, `$beforeUpdate` everything works fine. It is just observation, I don't know the real reason.

[__Here's test repo.__](https://github.com/rmuratov/objection-password-test)

```js
knex.schema
  .createTable('user', function(t) {
    t.increments('id').unsigned().primary();
    t.dateTime('createdAt').notNull();
    t.dateTime('updatedAt').nullable();
    t.string('email').unique().notNull();
    t.string('password').notNull();
  })
```

```js
const Password = require('objection-password')();
const Model = require('objection').Model;

class User extends Password(Model) {
  static get tableName() {
    return 'user';
  }

  $beforeInsert() {
    const createdAt = Date.now();
    this.createdAt = createdAt;
    this.updatedAt = createdAt;
  }

  $beforeUpdate() {
    this.updatedAt = Date.now();
  }
}
```

- node v10.14.1
- objection 1.4.0
- objection-password 2.0.0

**Comment by rmuratov** [comment]
I did try some debugging and it seems like `objection-password`'s `$beforeInsert` wasn't even called.

**Comment by rmuratov** [comment]
Ok, I'm dumb. I should've called super class' `$beforeInsert`/`$beforeUpdate`.

```js
async $beforeInsert(queryContext) {
  await super.$beforeInsert(queryContext);
  const createdAt = Date.now();
  this.createdAt = createdAt;
  this.updatedAt = createdAt;
}
```

**Comment by csherm08** [comment]
I'm also dumb, but this worked and i can't believe i didn't realize. Thanks!
