### ISSUE TITLE
Test w/ objection v2

### ISSUE THREAD

**Issue by JaneJeon** [scoutforpets/objection-password#18]
Hi, as simple as this library is, we should still test it for objection v2 (and v1, if you want).

This also gives you the opportunity to bump this plugin to v3.0.0 if you were to drop support for objection@1.

Thoughts? (e.g. do you want to support both v1 and v2)

P.S. if you want to look at an example of how to support both v1 and v2, see here: https://github.com/JaneJeon/objection-hashid/blob/master/index.test.js#L11
and here: https://github.com/JaneJeon/objection-hashid/blob/master/package.json#L50

**Comment by jamesdixon** [comment]
Resolved by #32
