### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [scoutforpets/objection-password#20]
This npm package needs a TypeScript types declaration file so that developers who enjoy writing with TS can use it with this package and have a better development experience. Would you like me to write one?

**Comment by hkyq** [comment]
Lol, I just searched typescript on this repo a few seconds and this came up. I am not a maintainer but that would be nice.

**Comment by jamesdixon** [comment]
@geopic a PR would be more than welcomed. Thank you!

**Comment by geopic** [comment]
Will get started on it soon then @jamesdixon , thanks

**Comment by severo** [comment]
Excellent. Could you publish it on npmjs?
