### ISSUE TITLE
Upgrade to bcrypt 2.0.0+

### ISSUE THREAD

**Issue by Tyler-Churchill** [scoutforpets/objection-password#9]
`warning bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
warning objection-password > bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes`

**Comment by jamesdixon** [comment]
Resolved via 09503c1. Will release a new version soon

**Comment by jamesdixon** [comment]
Just published 2.0.0
